version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pasteleria-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pasteleria
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: development
    container_name: pasteleria-api
    command: yarn start:dev
    restart: always
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: pasteleria
      JWT_SECRET: super-secret-token
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
